$('.owl-carousel').owlCarousel({
  loop:true,
  margin:40,
  nav:true,
  navText: ['<i class="fa fa-chevron-left"></i>', '<i class="fa fa-chevron-right"></i>'],
  autoplay:true,
  autoplayTimeout:3000,
  autoplayHoverPause:true,
  responsive:{
      0:{
          items:1
      },
      400:{
          items:2
      },
      768:{
          items:4
      }
  }
});
